### ISSUE TITLE
时至今日，腾讯已经干掉网页版微信了......

### ISSUE THREAD

**Issue by liepengGitHub** [smokingrain/WeChat#10]
`<error><ret>1203</ret><message>为了你的帐号安全，此微信号不能登录网页微信。你可以使用Windows微信或Mac微信在电脑端登录。Windows微信下载地址：https://pc.weixin.qq.com  Mac微信下载地址：https://mac.weixin.qq.com</message></error>`

**Comment by smokingrain** [comment]
干掉还不至于，部分账号确实登陆会失败。我也有账号被封号，就不能登陆。
