### ISSUE TITLE
作者辛苦了

### ISSUE THREAD

**Issue by chinaluopiao** [smokingrain/WeChat#2]
linux没有微信使用，只能用网页版真的很不方便，希望作者能够继续完善，加油

**Comment by smokingrain** [comment]
这个是windows项目，不过迁移linux也是可以的，目前出过类似版本在mac跑过，有部分功能不能用，大体上还是没问题的。

**Comment by wangbiaogg-git** [comment]
这个源码怎么跑起来..

**Comment by smokingrain** [comment]
[QRLoginWindow.java](https://github.com/smokingrain/WeChat/blob/master/src/com/xk/ui/main/QRLoginWindow.java)
找到这个类，直接当main方法运行。
