### ISSUE TITLE
找不到主类

### ISSUE THREAD

**Issue by SY-XU** [smokingrain/WeChat#5]
你好，运行Login文件可是报错：
错误: 找不到或无法加载主类 com.xk.ui.main.QRLoginWindow
请问是什么原因造成的，是jar包的路径问题吗？
谢谢！

**Comment by SY-XU** [comment]
自己找到了问题所在，是构建路径里的系统jar路径没有指定，给一个备用的jre1.8就可以解决问题。

**Comment by SY-XU** [comment]
还是想问一下大佬能不能解释一下，登陆的时候跳到wx2.qq.com网址然后就崩溃了，没想懂什么原因

**Comment by bridgeren** [comment]
1.找不到主类的解决方法，参见这篇博文的第六条[找不到主类](https://blog.csdn.net/chenleixing/article/details/44816629)
2.解决完这个问题后发现sun.misc.BASE64Encoder和opencv找不到jar包，参见这个博文
[sun.mics](https://blog.csdn.net/jbxiaozi/article/details/7351768)和[opencv](https://blog.csdn.net/jia20003/article/details/68944486?utm_source=blogxgwz0)
上面是我遇到的问题和解决方法，供大家参考

**Comment by smokingrain** [comment]
@bridgeren good job

**Comment by hu1732030** [comment]
老哥，自定义组件的代码，可否增加多点注释，第一次接触GUI编程，很多看起来有点头疼。
平时是做web开发的。想做点小工具耍耍。 谢谢老哥
