### ISSUE TITLE
opencv找不到包

### ISSUE THREAD

**Issue by qiweiview** [smokingrain/WeChat#7]
opencv找不到包

**Comment by smokingrain** [comment]
[#issuecomment-431730646](https://github.com/smokingrain/WeChat/issues/5#issuecomment-431730646)
可以参考这里

**Comment by smokingrain** [comment]
你把OPENCV相关的代码都去掉也可，反正不影响功能。

**Comment by qiweiview** [comment]
> 你把OPENCV相关的代码都去掉也可，反正不影响功能。

多谢多谢，跑起来了，正在学习。
识别那部分是不包含在微信客户端里是吗
