### ISSUE TITLE
解析微信消息是自己写的还是用的包？

### ISSUE THREAD

**Issue by scorego** [smokingrain/WeChat#8]
问一下，我最近再写一个小玩具，用的wechat-api。但是发现有些接口失效了，想问下作者你解析微信消息用的是自己写的类库还是引的现有的?xiexie

**Comment by smokingrain** [comment]
几乎所有API都在com/xk/utils/WeChatUtil.java,你可以看看，暂时没发现失效的接口.解析消息是直接从网页微信抓取的。
